// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWx_daVEm1TJp9Jb6QDJ-XBZ4cpV0kv1E',
    appId: '1:795200079650:web:6abe7655a3b3d4b174077b',
    messagingSenderId: '795200079650',
    projectId: 'geoggurostore',
    authDomain: 'geoggurostore.firebaseapp.com',
    databaseURL: 'https://geoggurostore-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'geoggurostore.appspot.com',
    measurementId: 'G-M21VMBWHMN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBodbkbyCzCuRzYEKxfliBmCYklh2-0yIo',
    appId: '1:795200079650:android:ae695ae7ef67bcfb74077b',
    messagingSenderId: '795200079650',
    projectId: 'geoggurostore',
    databaseURL: 'https://geoggurostore-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'geoggurostore.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfHlvelWfG47dbhq-5ztEE5scDLV6tXZU',
    appId: '1:795200079650:ios:cb975b194503f47074077b',
    messagingSenderId: '795200079650',
    projectId: 'geoggurostore',
    databaseURL: 'https://geoggurostore-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'geoggurostore.appspot.com',
    iosBundleId: 'com.example.geogguroStoreBoom',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfHlvelWfG47dbhq-5ztEE5scDLV6tXZU',
    appId: '1:795200079650:ios:cb975b194503f47074077b',
    messagingSenderId: '795200079650',
    projectId: 'geoggurostore',
    databaseURL: 'https://geoggurostore-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'geoggurostore.appspot.com',
    iosBundleId: 'com.example.geogguroStoreBoom',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWx_daVEm1TJp9Jb6QDJ-XBZ4cpV0kv1E',
    appId: '1:795200079650:web:da23d87470a8c05374077b',
    messagingSenderId: '795200079650',
    projectId: 'geoggurostore',
    authDomain: 'geoggurostore.firebaseapp.com',
    databaseURL: 'https://geoggurostore-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'geoggurostore.appspot.com',
    measurementId: 'G-EXMNS6S5ZM',
  );
}
